//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""HumanoidLand"",
            ""id"": ""ac505ae4-cd75-4993-bc6d-e13670f7892e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""dfeef1ad-f8ef-4d58-a20a-b01ce93bc3e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""d7a56f92-ae0b-46f5-b4d6-66a6bab5fe77"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeCamera"",
                    ""type"": ""Button"",
                    ""id"": ""59ff3e2e-8e40-4fb3-93f7-1cc67693afd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraDistance"",
                    ""type"": ""Value"",
                    ""id"": ""13eafbc6-567a-45c7-8f3d-a7f4216a6edc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Value"",
                    ""id"": ""73367224-a1ec-448c-9b8d-11a31fd6cab6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""dbb48152-903d-4dae-a61d-459611b96cef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Value"",
                    ""id"": ""e5f27e37-28ff-41fb-acdb-8ecae1bedab9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Activate"",
                    ""type"": ""Value"",
                    ""id"": ""6c0f5679-14da-4785-813e-abd6e11c8fbb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnOff"",
                    ""type"": ""Button"",
                    ""id"": ""c32fb440-4c25-4192-8d02-9d0ae7574378"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mode"",
                    ""type"": ""Button"",
                    ""id"": ""cc14ff92-60be-4002-987f-863c016dc2b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Character"",
                    ""type"": ""Button"",
                    ""id"": ""0fc246f6-e3e6-4bea-9c41-1e1d86df37fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""4e862b0c-9a51-4ac0-8a4c-6fee1f982472"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""599f9324-0a88-4d7b-b2ae-846200ba1bcd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""205fff06-924b-40e8-8b52-883ac5e758d6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9f81d080-c838-4ae0-860d-509bba97d8ea"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6303a16c-a2a6-4cb1-bd72-c3bf7bd28182"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2f423718-2787-422d-867c-5745326aa607"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86b94a85-c5e4-49cc-8ba3-07f72cf26b03"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.03,y=0.03)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b37c9b6-24ea-412c-a189-d7699a317d19"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54f50829-324d-48a9-9f4c-1f13202f3aaf"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c906b8e-a915-4b97-9f6c-ad190523f126"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055491b0-daf5-47b1-96eb-b73cecca910a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-0.4,max=0.4)"",
                    ""groups"": """",
                    ""action"": ""CameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0015eceb-948e-416e-855f-eecd7639115a"",
                    ""path"": ""<Gamepad>/dpad/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""538484c9-827f-42d2-8e6e-39c587811114"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7facad0f-724d-4b58-bd20-68bdf83554c6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60897247-2ed4-483f-a59c-98c5c54a8199"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84228b05-9382-4f95-b0ad-9ecc1d5a040c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fd2606b-33b0-408d-afbc-b4f684a1af01"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e90895c4-b445-48b2-ae5f-3fdf3344a124"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcea6afe-b932-4cf4-ace3-73180180bd16"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""592ded71-886d-4193-befd-5227edb78fc6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53ba4c73-e441-4a75-96bf-9dd022d90e36"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""057a064e-ab17-4356-86cf-ebd5683ea61f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd129f14-dafc-426b-b237-e19c8a663273"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ee6e00a-222c-4f2c-a7bc-1f2435086c94"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ee15b58-f39b-4a3f-8b98-8ecdab80fb84"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a10fb85-4b1d-428f-b92c-a6c3be82b955"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Character"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // HumanoidLand
            m_HumanoidLand = asset.FindActionMap("HumanoidLand", throwIfNotFound: true);
            m_HumanoidLand_Move = m_HumanoidLand.FindAction("Move", throwIfNotFound: true);
            m_HumanoidLand_Look = m_HumanoidLand.FindAction("Look", throwIfNotFound: true);
            m_HumanoidLand_ChangeCamera = m_HumanoidLand.FindAction("ChangeCamera", throwIfNotFound: true);
            m_HumanoidLand_CameraDistance = m_HumanoidLand.FindAction("CameraDistance", throwIfNotFound: true);
            m_HumanoidLand_Run = m_HumanoidLand.FindAction("Run", throwIfNotFound: true);
            m_HumanoidLand_Jump = m_HumanoidLand.FindAction("Jump", throwIfNotFound: true);
            m_HumanoidLand_Crouch = m_HumanoidLand.FindAction("Crouch", throwIfNotFound: true);
            m_HumanoidLand_Activate = m_HumanoidLand.FindAction("Activate", throwIfNotFound: true);
            m_HumanoidLand_OnOff = m_HumanoidLand.FindAction("OnOff", throwIfNotFound: true);
            m_HumanoidLand_Mode = m_HumanoidLand.FindAction("Mode", throwIfNotFound: true);
            m_HumanoidLand_SwitchCharacter = m_HumanoidLand.FindAction("Switch Character", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // HumanoidLand
        private readonly InputActionMap m_HumanoidLand;
        private IHumanoidLandActions m_HumanoidLandActionsCallbackInterface;
        private readonly InputAction m_HumanoidLand_Move;
        private readonly InputAction m_HumanoidLand_Look;
        private readonly InputAction m_HumanoidLand_ChangeCamera;
        private readonly InputAction m_HumanoidLand_CameraDistance;
        private readonly InputAction m_HumanoidLand_Run;
        private readonly InputAction m_HumanoidLand_Jump;
        private readonly InputAction m_HumanoidLand_Crouch;
        private readonly InputAction m_HumanoidLand_Activate;
        private readonly InputAction m_HumanoidLand_OnOff;
        private readonly InputAction m_HumanoidLand_Mode;
        private readonly InputAction m_HumanoidLand_SwitchCharacter;
        public struct HumanoidLandActions
        {
            private @InputActions m_Wrapper;
            public HumanoidLandActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_HumanoidLand_Move;
            public InputAction @Look => m_Wrapper.m_HumanoidLand_Look;
            public InputAction @ChangeCamera => m_Wrapper.m_HumanoidLand_ChangeCamera;
            public InputAction @CameraDistance => m_Wrapper.m_HumanoidLand_CameraDistance;
            public InputAction @Run => m_Wrapper.m_HumanoidLand_Run;
            public InputAction @Jump => m_Wrapper.m_HumanoidLand_Jump;
            public InputAction @Crouch => m_Wrapper.m_HumanoidLand_Crouch;
            public InputAction @Activate => m_Wrapper.m_HumanoidLand_Activate;
            public InputAction @OnOff => m_Wrapper.m_HumanoidLand_OnOff;
            public InputAction @Mode => m_Wrapper.m_HumanoidLand_Mode;
            public InputAction @SwitchCharacter => m_Wrapper.m_HumanoidLand_SwitchCharacter;
            public InputActionMap Get() { return m_Wrapper.m_HumanoidLand; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HumanoidLandActions set) { return set.Get(); }
            public void SetCallbacks(IHumanoidLandActions instance)
            {
                if (m_Wrapper.m_HumanoidLandActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMove;
                    @Look.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnLook;
                    @ChangeCamera.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnChangeCamera;
                    @ChangeCamera.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnChangeCamera;
                    @ChangeCamera.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnChangeCamera;
                    @CameraDistance.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCameraDistance;
                    @CameraDistance.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCameraDistance;
                    @CameraDistance.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCameraDistance;
                    @Run.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnRun;
                    @Run.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnRun;
                    @Run.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnRun;
                    @Jump.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnJump;
                    @Crouch.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCrouch;
                    @Crouch.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCrouch;
                    @Crouch.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnCrouch;
                    @Activate.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnActivate;
                    @Activate.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnActivate;
                    @Activate.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnActivate;
                    @OnOff.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnOnOff;
                    @OnOff.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnOnOff;
                    @OnOff.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnOnOff;
                    @Mode.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMode;
                    @Mode.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMode;
                    @Mode.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnMode;
                    @SwitchCharacter.started -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnSwitchCharacter;
                    @SwitchCharacter.performed -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnSwitchCharacter;
                    @SwitchCharacter.canceled -= m_Wrapper.m_HumanoidLandActionsCallbackInterface.OnSwitchCharacter;
                }
                m_Wrapper.m_HumanoidLandActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @ChangeCamera.started += instance.OnChangeCamera;
                    @ChangeCamera.performed += instance.OnChangeCamera;
                    @ChangeCamera.canceled += instance.OnChangeCamera;
                    @CameraDistance.started += instance.OnCameraDistance;
                    @CameraDistance.performed += instance.OnCameraDistance;
                    @CameraDistance.canceled += instance.OnCameraDistance;
                    @Run.started += instance.OnRun;
                    @Run.performed += instance.OnRun;
                    @Run.canceled += instance.OnRun;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @Crouch.started += instance.OnCrouch;
                    @Crouch.performed += instance.OnCrouch;
                    @Crouch.canceled += instance.OnCrouch;
                    @Activate.started += instance.OnActivate;
                    @Activate.performed += instance.OnActivate;
                    @Activate.canceled += instance.OnActivate;
                    @OnOff.started += instance.OnOnOff;
                    @OnOff.performed += instance.OnOnOff;
                    @OnOff.canceled += instance.OnOnOff;
                    @Mode.started += instance.OnMode;
                    @Mode.performed += instance.OnMode;
                    @Mode.canceled += instance.OnMode;
                    @SwitchCharacter.started += instance.OnSwitchCharacter;
                    @SwitchCharacter.performed += instance.OnSwitchCharacter;
                    @SwitchCharacter.canceled += instance.OnSwitchCharacter;
                }
            }
        }
        public HumanoidLandActions @HumanoidLand => new HumanoidLandActions(this);
        public interface IHumanoidLandActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnChangeCamera(InputAction.CallbackContext context);
            void OnCameraDistance(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
            void OnActivate(InputAction.CallbackContext context);
            void OnOnOff(InputAction.CallbackContext context);
            void OnMode(InputAction.CallbackContext context);
            void OnSwitchCharacter(InputAction.CallbackContext context);
        }
    }
}
